### ISSUE TITLE
Refactor some vision backend code

### ISSUE THREAD

**Issue by beijbom** [beijbom/coralnet#102]
Refactor “classify task” so that it is easier to test without using spacer.
Split tasks.classify_image() so that there is a base function which takes (image_id, scores, label_objs, classifier) and does not have to call direct_s3_read(). This base function probably just has to call _add_annotations(), call _add_scores(), and set img.features.classified = True.

**Comment by StephenChan** [comment]
@beijbom Seems like everything in this issue has been addressed last year, right?

**Comment by beijbom** [comment]
Yeah, let's close it.
