### ISSUE TITLE
Public API documentation on the website

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#190]
The documentation would consist of a brief overview, similar to the API-draft Google Doc we've been writing, and details on each public endpoint / URL of the API.

The documentation could live on the website in the user help section (#127), at a URL like `/help/api`.

django-rest-framework has some support and for documenting an API: http://www.django-rest-framework.org/topics/documenting-your-api/
The gist of it is that we would write triple-quoted docstrings for our API-view functions, such as the following, and they should end up in the API documentation:

```python
class UserList(generics.ListCreateAPIView):
    """
    get:
    Return a list of all the existing users.

    post:
    Create a new user instance.
    """
```

And then on top of that, we would use one of several third-party apps to go on top of django-rest-framework and provide a nice documentation interface. For example, drf-yasg, DRF-OpenApi, Django REST Swagger. These are listed in the previous link as well.

Also consider to what extent our API should be self-describing: http://www.django-rest-framework.org/topics/documenting-your-api/#self-describing-apis

A lot of endpoints are going to have similar parameter formats and response formats. To avoid writing the same documentation twice, consider using references and definitions as described here: https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/v2.0/REUSE.md
For example, a common Metadata definition would save us from having to describe latitude, longitude, aux1, aux2, water_quality, etc. a million times. In general, we could have one definition per database model.

**Comment by StephenChan** [comment]
Hmm... part of this should go in the Beta 2 milestone, but as usual, the scope can be pared down.

We probably want:

- Public documentation pages.
- Brief overview of the API.
- Explanation of API authentication.
- Specifications of each public endpoint.
- Simple examples of each public endpoint.

We can probably defer:

- Any sort of automation/generation. Especially if we just have the deploy endpoints for now. We can just manually write up a page using Markdown or something.

**Comment by StephenChan** [comment]
It looks like this should be my next task. Sound good, @beijbom ?

Again, I can keep it simple and defer auto-generation, unless it looks like it's really easy to set up.

While the API is still in 'internal testing' mode, I can make the docs live at the URL `/help/api`, but without linking to it from `/help`.

**Comment by beijbom** [comment]
Agreed. Let’s keep it simple for now. It its good to get something up for
the beta testers.

**Comment by StephenChan** [comment]
https://coralnet.ucsd.edu/pages/help/api/

Here's something. So far it's basically the same as the demonstration you made earlier this week, but explained in more detail. I didn't fill in the 'Endpoints' section yet, and we can probably format the document a little more nicely.

**Comment by beijbom** [comment]
Thanks @StephenChan . Looks good so far.

**Comment by StephenChan** [comment]
Updated that page, filling out the 'Endpoints' section at the end.

I was originally thinking of adding examples to the 'Endpoints' section, but honestly that would feel redundant at this point. The 'How to Use' section covers all the API use cases so far, and already has examples. But when we add more endpoints later, the possible API use cases probably won't be so linear, and we can then start adding examples to 'Endpoints'.

Also, we still only have plain curl examples. For R examples, since it seems like neither of us has used R before, I think we should first work with NOAA to make sure they've gotten something working. Then we could actually base the R examples on their code, which in the end is likely to be cleaner than what we can come up with ourselves.

**Comment by beijbom** [comment]
I'm not sure I like the division between "how to use" and "endpoints". I think I'd have organized it directly by endpoints and include examples of a call in each language under each endpoint subsection. Ideally each in an expandable section although I'm not sure our support pages allow it?

We could then add a list of tutorials on a separate page. Here the stuff you put in the "how to use" section could go.

**Comment by StephenChan** [comment]
I think you're right about having separate pages for basics/tutorials vs. endpoints, especially in the long run when we have more endpoints. I can go ahead and do that, and copy the 'how to use' examples to the endpoints page.

> Ideally each [endpoint] in an expandable section although I'm not sure our support pages allow it?

They don't at this point. We could probably implement such a thing with moderate effort, though. We can always include HTML tags when writing Markdown, so we can delineate sections with `<div class='section'>` or something. Then we can customize the Django template for those pages, so that it runs some Javascript which does something special with those particular div elements.

**Comment by StephenChan** [comment]
Updated: https://coralnet.ucsd.edu/pages/help/api/

The how-to guide is now linked as 'Tutorial', and the endpoint details are linked as 'Reference'. All the info should be updated for the API tweaks I just made. The Reference page now has request/response examples as well.

**Comment by StephenChan** [comment]
Missed this issue when rounding up remaining tasks. I'm inclined to call it done for now, though. I'll make separate issues for:

1. R and Python examples. This can be moved up in priority again if someone requests this.

2. Automated documentation. This is only needed when we start creating many more API endpoints.

**Comment by beijbom** [comment]
sg
