### ISSUE TITLE
API endpoint to deploy classifier

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#231]
Currently, machine-classifying an image using CoralNet requires uploading that image to a source. The image can then be classified using that source's classifier, and the image is also used to further train the source's classifier.

With this API endpoint, you would specify a source's classifier to use, upload an image to be classified, and get a classification result back. The image to be classified doesn't get saved to any source. Benefits:

- The set of images used for training can be different from the set of images one wants to classify.
- Not every image one wants to classify has to be uploaded permanently to a CoralNet source, nor does it have to go through the whole training pipeline. This reduces CoralNet's storage costs and training-related compute costs, and speeds up the workflow.
- Since uploads are done via API, the image upload process can be made more robust using a script with error handling, as opposed to a web-form upload which may have to be supervised manually.

The majority of issue #189 (API basics) would have to be done before this issue.

**Comment by beijbom** [comment]
@StephenChan : is this issue complete?

**Comment by StephenChan** [comment]
Looks like it. This issue doesn't really get into specific requirements, and deploy is indeed working.
