### ISSUE TITLE
Enable support for different feature extractors.

### ISSUE THREAD

**Issue by beijbom** [beijbom/coralnet#235]
- Add string field to Source model to indicate which version of the feature extractor the source uses. 
- For all existing sources set the legacy extractor.
- Set the new feature extractor as default for new sources. Users can change this to the old extractor during source creation.
- Allow users to change extractor in the source admin page. 
- If the feature extractor is changed, warn user and wipe all features and classifiers from source.
- Add valid choices for feature_extractor_names to vision_backend settings.

**Comment by StephenChan** [comment]
1) Just to confirm the relative priorities of issues here - the new spacer rollout would happen before the new feature extractor rollout, right?

2) On this:

   > - Allow users to change extractor in the source admin page.

   Although maybe not necessary, it's worth also considering issue #92 on how to present the options. We would now have two backend-related settings, one for confidence threshold and one for feature extractor. The thing is, both require some explanatory text, so I don't think they'll be too lonely on a single 'backend settings' page.

3) Note from email discussion on how the code would change:

   > The extract_feature message has a string "feature_extractor_name". I'm planning to read that out from the source. So for this ticket we just need to add a string choice field to the source and add the valid choices to settings.

**Comment by beijbom** [comment]
Regarding priorities. The reality is that we will have a pretty large feature-branch loop unfortunately. Basically, we will need to roll-out python3 and the new spacer at once. This means that once we cut the python3 branch for
https://github.com/beijbom/coralnet/issues/59, we need to complete this ticket, along with #264 and #302 into that branch before we can merge to master an update the server. We should also plan a few days of downtime when we do that so that we can do proper shake-outs.

**Comment by StephenChan** [comment]
Huh. Well, that's going to be fun then. Do you think we could ease things a bit by implementing some of this ticket in advance - like, implementing the extractor-choice field, but with only one option instead of two?

Also, regarding #59, I could aim to master-merge as many 'safe' Py3 porting changes as possible, before really carving out that final Py3 branch which would be merged along with spacer. Ideally, that earlier merging step would include porting everything that's not too closely tied to the vision backend.

**Comment by StephenChan** [comment]
Implemented in PR #360.
