### ISSUE TITLE
Address Unicode tests' dependency on OS-specific collation

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#272]
See PR #271. Two Unicode tests were passing on PC/Mac dev environments, but failing on Travis and the Linux staging server. Reversing the order of the expected lines reversed the respective pass/fail results. Ideally, all environments would sort these lines the same way.

Possibly related: https://stackoverflow.com/questions/22534484/postgresql-incorrect-sorting

This issue may or may not be easier to deal with in Python 3 / Django 2, since Py3 in particular brings a lot of Unicode improvements.

**Comment by beijbom** [comment]
@StephenChan : another way to look at this is: does the sorting need to be consistent in this case? If not, just change the test to be "either this or this works".

**Comment by StephenChan** [comment]
Yeah, that's fair - I guess the fact that different OS's get different results just makes me a bit nervous in general. But in the big picture, just making the test suite pass on all systems is Beta 2 priority, while the sorting consistency is Beta 3 or 4. So I'll consider that when I take a closer look.

Also, if we do decide this sorting case is worth testing, I guess it makes sense to have one test focus on 'does Unicode work?', and another test to focus on 'does Unicode sort properly?'. That way the tests are more modular.

**Comment by StephenChan** [comment]
Okay, it's almost certainly a database collation issue. And that, in turn, indeed depends on the locales installed in each OS.

- I tried plain Python sorting on my Windows dev machine and the Linux production instance, with `sorted(['A', 'い'])`. Both systems put 'A' first. So no difference here.

- I tried queryset sorting in manage.py shell: `Source.objects.filter(name__lt='い')`. Windows dev gets all sources starting with English letters. Production gets nothing. In other words, Windows put English letters before Japanese kana, and Linux did the opposite.

- I checked the collation of each database with `SHOW lc_collate;` on the PostgreSQL prompt. Windows dev gets `English_United States.1252`. Production gets `en_US.UTF-8`.

- The `WITH v(title) AS ...` commands in [this SO answer](https://stackoverflow.com/a/22535373/) also got different results between Windows dev and Linux production.

So the first question is: which collation is better? Code page 1252 is Windows specific and only supports Western characters, while UTF-8 is a universal standard which supports characters from all languages. So I'm inclined to say the one currently used in production, `en_US.UTF-8`, is better.

Next question: can Windows and Mac dev environments be changed so that they used the same collation as production? Maybe, but it seems more trouble than it's worth right now:

- I looked at the other available collations in my Windows install of PostgreSQL. When I try to create a database, the collation dropdown has `English_United States.1252`, `C`, and `POSIX`. `C` gets the same results as `English_United States.1252` for 'A' versus 'い' (that is, it doesn't match production). And it just doesn't let me select `POSIX`.

- There is an internationalization library called [ICU](https://www.2ndquadrant.com/en/blog/icu-support-postgresql-10/) which could potentially help achieve collation consistency, if all systems used ICU with PostgreSQL. For Linux, PostgreSQL must be built with the ICU library; we'd depend on Amazon RDS to do this (Amazon [mentions ICU support here](https://aws.amazon.com/about-aws/whats-new/2018/05/amazon-rds-supports-postgresql-10-for-aws-govcloud/), so chances are they do build with ICU). However, I don't know how to get ICU support in Windows and Mac.

- If we did want to change the production database to ICU collation, we'd have to create a new database and port all the data to it, since you can't change a PostgreSQL DB's collation in-place. So it'll require a lengthy downtime, and it's not a decision to make on a whim. We'd probably want a solid reason to do it.

## Conclusion

- Making collations consistent between systems seems to be a relatively new thing in the database admin world. So, for now, maybe it's most reasonable to treat the sorting issue as a quirk instead of a bug. If collation issues end up breaking something more significant in CoralNet, then we could re-evaluate the situation then.

- At least the collation used in production seems to be the better one (UTF-8, not 1252 / whatever similar scheme Mac uses). That's better than the opposite situation.

- As far as these unit tests are concerned, I'll just change them so that they don't depend on the collation.

**Comment by StephenChan** [comment]
> As far as these unit tests are concerned, I'll just change them so that they don't depend on the collation.

And that's done with PR #273.

As I previously mentioned, I'll consider the collation inconsistency as a quirk instead of a bug, so that won't get its own issue for the time being.
