### ISSUE TITLE
`request_json` fields json or dicts?

### ISSUE THREAD

**Issue by beijbom** [beijbom/coralnet#280]
@StephenChan : should the `request_json` and `response_json` fields be JSON encoded strings or python dicts? From the comment in the model I understood a JSON encoded string but from this line is looks like you are just setting as a dict.

https://github.com/beijbom/coralnet/blob/f96549ae2108fba76409bbdf2ef9077fec79d1c8/project/vision_backend_api/views.py#L55

**Comment by beijbom** [comment]
Looking at your tests it I will assume you meant it should be a dict. I'll assume that for now.

**Comment by StephenChan** [comment]
https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#jsonfield

> A field for storing JSON encoded data. In Python the data is represented in its Python native format: dictionaries, lists, strings, numbers, booleans and None.

**Comment by beijbom** [comment]
Tnx.
