### ISSUE TITLE
IOError at /label/<id>/example_patches_ajax/ - image file is truncated (<number> bytes not processed)

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#282]
I guess we don't have an issue for this error yet, but I'm pretty sure it's been happening for a while. And fairly frequently, too.

Example after issue #275 was resolved: https://coralnet.ucsd.edu/admin/errorlogs/errorlog/2438/change/
Image in question: image ID 68379
Happened at the `im = im.convert('RGB')` line.

Example before issue #275 was resolved: https://coralnet.ucsd.edu/admin/errorlogs/errorlog/2069/change/
Image in question: image ID 1192943
Happened at the `region = image.crop(box)` line.

This link describes a similar error message: https://stackoverflow.com/questions/12984426/python-pil-ioerror-image-file-truncated-with-big-images

**Comment by beijbom** [comment]
I think the problem is that `im.convert` requires image metadata for PIL to know what color space the image is in. What I suggest is that we catch the `IOError` and then run a "poor mans" conversion, similar to what we do in spacer. That may not handle the most exotic color spaces correctly, but it will do something reasonable in most cases. 


```
_ = np.array(im)  # For some images np.array returns an empty array.
im = np.array(im)  # Running it twice fixes this. Don't ask me why.

if len(im.shape) == 2 or im.shape[2] == 1:
   im = gray2rgb(im)
im = im[:, :, :3]  # only keep the first three color channels

def gray2rgb(im: np.ndarray) -> np.ndarray:
    """
    Convert gray image to RGB image
    :param im: gray image to be converted
    :return: RGB image
    """
    w, h = im.shape
    ret = np.empty((w, h, 3), dtype=np.uint8)
    ret[:, :, 0] = im
    ret[:, :, 1] = im
    ret[:, :, 2] = im

    return ret
```
