### ISSUE TITLE
More API tweaks to URLs and response structures

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#286]
I was going to update the production server, but then realized that PR #283 (API singular nouns) would also take effect if we do so. Meanwhile, I suggested more spec tweaks in the API Google doc, but haven't implemented those yet. I'd rather update those all at once so that they're easier to keep track of.

So, here are the spec tweaks I suggested in the API Google doc, along with a few others I looked into today. Just want to make sure we're on the same page (@beijbom ) before implementing them:

1. `/api/classifiers/:id/deploy` -> `/api/classifier/:id/deploy`

   Another plural to singular URL change. This was already suggested and accepted in the Google doc.

2. `/api/deploy_status/:id` -> `/api/deploy_job/:id/status`
   `/api/deploy_result/:id` -> `/api/deploy_job/:id/result`

   It might be cleaner in the long run to have the API URLs indicate what the internal models actually are. This was already suggested in the Google doc.

3. In the label fields for `deploy_job/:id/result`, it should use the custom short code used by the classifier's source, rather than the default short code. This makes it more consistent with CSV import/export of annotations. This was already suggested in the Google doc.

4. Change the `token-auth` URL to `token_auth` (underscore, not hyphen) to match all the other URLs on CoralNet: `deploy_job`, `annotation_tool`, `images_preview_ajax`, `entry_detail`, etc. (Not sure why I used hyphen in the first place, oops.)

5. Some of the error responses from our API (the ones crafted by django-rest-framework's internals, not by our code) are not compliant with jsonapi.org.

   Example:
   ```json
   {
     "detail": "Request was throttled. Expected available in 60.0 seconds."
   }
   ```

   How to make it compliant:
   ```json
   {
     "errors": [
       {
         "detail": "Request was throttled. Expected available in 60.0 seconds."
       }
     ]
   }
   ```

   Since I already wrote SOME compliant error responses, this is also a matter of consistency, not just bikeshedding. Anyway, although the non-compliant ones are from django-rest-framework, I think I know where the customization hook is to change the response.

6. Successful responses of `deploy_status` are not jsonapi.org complaint:

   Example:
   ```json
    {
      "data": {
        "successes": 0,
        "failures": 1,
        "total": 2,
        "status": "In Progress"
      }
    }
   ```

   How to make it compliant:
   ```json
    {
      "data": [
        {
          "type": "job",
          "id": "7",
          "attributes": {
            "successes": 0,
            "failures": 1,
            "total": 2,
            "status": "In Progress"
          }
        }
      ]
    }
   ```

   This IS pure bikeshedding, but might as well do it now while the API is still new. When I originally coded this, I was just roughly following jsonapi.org without always being too careful. Just now, I went through our tests and printed various response bodies, then pasted them into this validator tool to check compliance - it's a bit old, but seems to work well enough: https://jsonapi-validator.herokuapp.com/

7. Successful responses of `deploy_result` are not jsonapi.org complaint:

   Example:
   ```json
    {
      "data": {
        "images": [
          {
            "url": "URL 1",
            "points": [
              {
                "column": 10,
                "classifications": [
                  {
                    "label_id": 1,
                    "score": 1.0,
                    "label_name": "A",
                    "default_code": "A"
                  }
                ],
                "row": 10
              }
            ]
          },
          {
            "url": "URL 2",
            "errors": [
              "Classifier of id 33 does not exist."
            ]
          }
        ]
      }
    }

   ```

   How to make it compliant:
   ```json
    {
      "data": [
        {
          "type": "image",
          "id": "URL 1",
          "attributes": {
            "url": "URL 1",
            "points": [
              {
                "column": 10,
                "classifications": [
                  {
                    "label_id": 1,
                    "score": 1.0,
                    "label_name": "A",
                    "default_code": "A"
                  }
                ],
                "row": 10
              }
            ]
          }
        },
        {
          "type": "image",
          "id": "URL 2",
          "attributes": {
            "url": "URL 2",
            "errors": [
              "Classifier of id 33 does not exist."
            ]
          }
        }
      ]
    }
   ```

   Note that jsonapi.org requires an `id` member for each resource object in `data`. But in this case, `data` describes images that aren't in the database, and thus have no database ID. However, we can just set the `id` to something that's guaranteed to be unique within this particular response. In this case the image URL should work. It still doesn't hurt to provide the URL in a `url` attribute as before, even though it becomes a bit redundant.

**Comment by beijbom** [comment]
Thanks for listing these @StephenChan . These all make sense -- as you mention, the main ones were discussed and agreed on previously. I have also learned a new word: bikeshedding! :)

**Comment by StephenChan** [comment]
Cool. Yeah, it doesn't have anything to do with bicycles losing hair.

I'm almost done implementing these, but I think point 7 could use an addendum. The POST request format for `deploy` should also be changed, basically matching the changes to the `deploy_result` response (except with the `id` attributes excluded).

The main reason is consistency between `deploy` and `deploy_result`. Also, this would make `deploy` match the format the jsonapi.org spec prescribes for resource-creation POST requests: https://jsonapi.org/format/#crud-creating

- When we make deploy requests, we're not actually saving `Image` objects in the database (although we are creating temporary images in a sense). So it's not exactly the same situation, but the spec doesn't cover many POST parameter situations, so we might as well adopt the format suggested here.

**Comment by StephenChan** [comment]
Should be done in PR #287.
