### ISSUE TITLE
API job monitor for developers

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#293]
Something similar to the `backend_overview` page, but for API jobs, so that we can see info such as the following:

- How many API jobs are currently active?
- What's the status of each job, when did each job start, and who started it?
- Any errors in the recently completed jobs?

Relatedly, we may also want AWS alerts to help with monitoring activity spikes.

**Comment by beijbom** [comment]
Suggestion to also display (some subset of (?)) this information to the users.

**Comment by beijbom** [comment]
@StephenChan : this issue is complete, right? Per https://coralnet.ucsd.edu/api_management/jobs/.

**Comment by beijbom** [comment]
... assuming it is, so closing.

**Comment by StephenChan** [comment]
Oh. Yeah, seems I forgot to close this. The 'AWS alerts' part may or may not be covered, but it can be a separate issue if we think our current alerts are lacking.
