### ISSUE TITLE
Assessing affected data from annotation tool zoom/rotation bugs

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#330]
Issues #107 (rotation) and #319 (zoom) are fixed, but the bugs were present for months, and many sources/images annotated on CoralNet during that span could have incorrect annotations as a result of the bugs.

Here are some possible actions to take:

## 1. Scan the database for possible affected sources/images

For the orientation issue, I believe we're looking for images that:

- Had confirmed annotations added on 2020/03/24 or later, AND
- Have a non-default EXIF orientation value

EXIF orientations take a while to scan for, since the image file has to be read from S3. If we were scanning ALL images in the database for this, it'd take roughly 10 days, based on a test run I did on up to 20 images per source. However, capping the annotation date to 2020/03/24 or later would hopefully narrow down the scan a fair bit.

That being said, I'm not sure how long it takes to scan for the annotation date (which generally has to be checked for all images). I'll have to try it out. We have a field for upload date, but for annotation date we'd have to dig through the annotation history entries of each image.

For the zoom problem, we'd just take the images that were annotated 2019/07/30 or later. That would actually be a superset of the images affected by the rotation problem, for what that's worth. Though the two problems are different in terms of affected browsers. Actually... now I want to confirm whether Safari had the zoom problem or not. I'd like to think the Chromium zoom thing was a bug, but it could have been an obscure design decision. (EDIT: Epiphany browser doesn't have the zoom issue with the pre-Chromium-fix version of the annotation tool. So, Safari probably didn't have the zoom issue either.)

In any case: for the possibly affected images, we'd write a CSV containing the source ID, image ID, 'last annotated' date, EXIF orientation value (if 2020/03/24 or later), and image dimensions.

## 2. Publish a list of possible affected source and image IDs

We could attempt to go through the affected sources and images and double check their annotations ourselves. But the ecologists who annotated the images should know which browser they used and whether they were aware of the annotation tool bugs. Not to mention, they're familiar with their own labelset and reef region. So, it's probably best if we leave the double checking up to them.

One way to get them started is to publish a list (or lists) of possible affected source and image IDs, based on the criteria above. This is relatively simple on our end, but if there are hundreds of affected image IDs for a particular source, it's going to be quite tedious and error-prone for them to type in those images' URLs one by one and do the checks. So I guess we'll see how many affected images we have.

## 3. Add new filters on the Browse Images page: last confirmed annotation date, and/or EXIF orientation value

This would make it less tedious to browse through a large set of potentially-affected images. Instead of typing image IDs, source owners could use the 'last annotated' search filter - for example, searching for images which were last annotated 2019/07/30 or later.

This filter, along with a 'sort by last annotated' option, is likely to be generally useful anyway. It's been brought up in issue #46. The only thing is that last-annotated is likely to be a slow filter unless we add a 'last annotated' database field to track it. In which case, we have to add the field, and make sure the field is updated or nulled-out at the appropriate times. We'll also have to pre-populate the field with a data migration, perhaps prioritizing recent sources in the short term if it's a slow operation. Nothing too scary, but requires a reasonable effort to make sure it's implemented correctly and in a time-sensitive manner.

An EXIF orientation filter (and database field - again, too slow otherwise) could also help identify potentially-affected images, particularly for people who are sure they used Firefox or Safari. Additionally, we'd probably need this database field if we implement a source-level 'respect EXIF orientation' option (will make a separate issue on this). Otherwise, though, it seems like a less useful field compared to annotation date. Arguably, it's as nice to have as some of our other metadata fields like camera model and water quality. And it would be relatively easy to maintain - just set at image upload time, and we're done. Not sure if that's enough to justify the addition though.

## 4. Make it easier to double check existing annotations in the annotation tool

I believe we've had a few ideas and requests of this nature over the years (#194 is related). Maybe this is the time to implement a couple of simpler ideas, now that we are directly asking people to double check their annotations. Or not. I suppose we'll see where we are on time after the previous items are addressed to satisfaction.

Idea 1: Have a setting that colors annotated points by functional group (matching the label buttons' colors) instead of by annotation status. For example, purple hard coral, red other invertebrates, yellow algae. The 'unannotated' and 'selected' colors (already customizable) would still be there with their usual meanings, but annotated unselected points (whether 'confirmed' or not) would be colored by functional group. If an image has been fully annotated, then all the colors should only indicate functional groups.

Idea 2: Have a setting that writes label short codes (perhaps up to X characters, X being another setting) next to the points, instead of writing point numbers next to the points. So instead of "1" "2" "3", you'd see "CCA" "Turf" "Porit" next to the points. Or "CCA" "Tur" "Por" if limiting to 3 characters. If you use this in tandem with the above idea of coloring by functional group, it could become much easier to verify the annotations at a glance.

**Comment by beijbom** [comment]
Hey. Sorry for brevity— on my phone.

An alternate route for 2&3 is:
Publish affected sources to the users.
Ask users to email us if they want to check their source.
If so: generate and share a google doc with links to each possibly affected
image, ordered by annotation date. The user can then click on the links,
one after one, and they will open in a browser tab where they can verify
them.

That way we don’t have to make a bespoke exif filter function that isn’t
really useful going forward.

We could also pre-generate such lists for each source in a g-doc and
pre-share With everyone (one source per tab). Should be secure but maybe
not best practice.

The other improvements in 3 and 4 are nice to have a bit not really needed
for this IMO.

**Comment by StephenChan** [comment]
Yeah, that Google doc idea could help - though the tabs idea could be onerous if there are a lot of sources. I guess we'll see how much affected data there is first. I'm also leaning toward not adding an EXIF-orientation filter if possible.

Also, I just looked into this:

> Actually... now I want to confirm whether Safari had the zoom problem or not. I'd like to think the Chromium zoom thing was a bug, but it could have been an obscure design decision.

I tested the zoom issue in the 'Epiphany' Web browser for Linux, which is the closest thing I can get to Safari without having a Mac (Epiphany and Safari run on the WebKit engine). Epiphany doesn't have the zoom issue with the pre-Chromium-fix version of the annotation tool. So, Safari probably didn't have the zoom issue either.

**Comment by StephenChan** [comment]
Results are in for the zoom issue. I made a list of images whose latest manual annotation (not imported, robot, or alleviate) happened between 2019/07/30 00:00 and 2020/06/12 06:00. Stats:

- 153470 images
- 339 sources
- Top 10 image counts from sources: 15258, 12676, 4968, 4800, 4728, 4198, 4111, 3671, 3387, 3100
- Sources with 500 or more images on the list: 64
- Sources with 100 or more images on the list: 142
- Sources with 20 or more images on the list: 260
- 33393 images from 2020/03/24 00:00 or later

So yes, a lot happens in a year. I checked 16 random images from the list, all from different sources and dates, to make sure that the annotations weren't just imported, alleviate, or robot.

For the zoom issue at least, I think the high image count and source count would make the list publishing or G-doc publishing methods too cumbersome. I would favor the annotation_date Browse filter idea instead.

I'll get to analyzing the rotation issue next.

**Comment by kriegman** [comment]
Stephen,

Can you export a list of sources numbers that are affected. I want to see
if any of these are ones that QImin has been using for
training. We've been considering removing those from the training set, and
retraining the final networks.

David

**Comment by StephenChan** [comment]
Sure, I'll email you the list of affected sources.

**Comment by StephenChan** [comment]
Results are in for the rotation issue. I scanned the 33393 images that got manual annotations between 2020/03/24 00:00 and 2020/06/12 06:00. Stats:

- 1562 images, across 19 sources, have EXIF orientation values other than 1.
  - 789 have a value of 8 (rotated 90 degrees right).
  - 534 have a value of 6 (rotated 90 degrees left).
  - 239 have a value of 3 (rotated 180 degrees).
- Image distribution across the 19 sources: 426, 311, 222, 176, 161, 63, 46, 33, 30, 26, 18, 17, 16, 8, 4, 2, 1, 1, 1.
- Only 4 images are nearly square, and these 4 all belong to the same source. The remaining images have an aspect ratio of 1.328 or higher (or the equivalent for portrait orientation).
- 2020/03/24 00:00 refers to the date when Safari could have started exhibiting the bug. For Chromium, 2020/04/07, we have only 1196 potentially affected images instead of 1562. For Firefox, 2020/06/02, we have only 63 potentially affected images.

I think the list publishing or G-doc publishing ideas would be much more feasible for this rotation issue, compared to the zoom issue, due to the smaller numbers of sources/images.

When listing the potentially affected images, we should highlight the 180 degree rotation cases and the near-square cases separately from the rest, since these cases are much harder to notice by inspection. We should also note which ones were potentially affected in Firefox. This can help people narrow down what to check, if they are certain they used Firefox.

**Comment by StephenChan** [comment]
Sorry for the long delay in following up here. I guess this issue was pretty demoralizing to begin with, and then the fact that I was also answering many questions on the side (from various people) made it harder to concentrate and ended up burning me out. I'm not even looking at this issue this week, but I'll give it another go next week. The first thing I'll do is post more details about the annotation-date Browse filter idea.

**Comment by kriegman** [comment]
Thanks for the update. That was discouraging, but mistakes happen. I think
the actual data impact may be fairly low.
Qimin and removed all suspect images/sources from the training data and
basically got the same results as before.

David

**Comment by StephenChan** [comment]
That's good to hear at least.

**Comment by StephenChan** [comment]
All right, here we go. For the proposed image-level 'annotation date' feature, I was thinking about what the exact semantics of this feature should be, so that it:

- Could be used to find images affected by the zoom issue
- Also can be used for other bookkeeping purposes
- Isn't too complex or confusing

My idea now is that we shouldn't add a date field, but rather **a foreign key field pointing to the image's latest-updated annotation**.

Say we call the field `last_annotation`. Then `last_annotation.annotation_date` gives us the date of the latest-updated annotation in the image, or null if the image has no annotations. And `last_annotation.user` can tell us if the latest annotation was done by a robot, Alleviate, importing, or by a user on the annotation tool.

## Database implementation

This `last_annotation` field would be updated whenever an annotation from the image is updated. It would be set to null if all of the image's annotations are deleted. So the update semantics, at least, would be fairly simple.

To implement the updating, we could probably use an Annotation post-save signal, similar to what django-reversion uses.

For deleting, there are a few cases where we delete annotations:

- Updating unconfirmed annotations with the latest classifier.

- Regenerating points on an image with unconfirmed annotations.

- Importing new points/annotations.

- Using the 'Delete annotations' button on the Image Detail page.

In each case, we delete ALL of the image's annotations at once (which means we set last annotation to null), followed by possibly adding new annotations in their place. We could maybe use Annotation post-delete signals here, as long as we don't use batch-delete operations which skip the signals.

A good test for search-query performance would be any source with a lot of annotations, such as source 372.

## Finding images affected by the zoom issue

Using the field described above, to find images affected by the zoom issue, we'd search for images where:

- `last_annotation.annotation_date` is between 2019/07/30 and 2020/06/12, and
- `last_annotation.user` is a registered user (indicating an annotation tool save).

The idea behind the user condition is that, if ANY annotations were made by a user in the annotation tool, they almost always come AFTER other types of annotations:

- When points/annotations are imported, all previous points/annotations for that image are deleted. So it's not possible to have any other type of annotations before imported ones.

- Generally, if Alleviate was involved at all, Alleviate would have either come before any annotation tool work, or Alleviate would have annotated all the points. The only possible exception would be the following odd case: enter the annotation tool with a high Alleviate threshold, make some annotations, set a lower Alleviate threshold, and then re-enter the annotation tool so that Alleviate completes the annotations.

- When robot annotations are updated, that means the points were not confirmed to begin with. The only way to have robot annotations updated later than confirmed annotations is to confirm a subset of the points, then let another round of robot training and classification happen. This is of course possible, but not common since users typically annotate all of an image's points in one go.

It would be more precise if you could look up images that had any *annotation-tool* activity saved from 2019/07/30 to 2020/06/12. Not just any annotation activity. In terms of an alternative implementation, that could either mean:

- Saving a 'last annotation' field for each possible annotation method: annotation tool, Alleviate, importing, classifier. But this might be too much additional complexity.

- Making it a 'last annotation by annotation tool' field instead, ignoring Alleviate, importing, and classifier activity. But this might be a little too bespoke to this use case.

## Workflow for checking images affected by the zoom issue

![1_browse-images__annotated](https://user-images.githubusercontent.com/857711/89072387-51590900-d32d-11ea-80f6-a5937ca450a7.png)

- (2): If the source owner has more info such as who used which browser when annotating, then they could limit the search to a specific annotation-tool user. Of course, if they also think only a specific set of images was affected (or they only care about a specific set), they can use the image metadata filters too.

- (2): The first dropdown would have choices of Annotation Tool, Alleviate, Importing, and Classifier (Unconfirmed). The second dropdown would only appear if the first choice was Annotation Tool.

- (3) Sort direction shouldn't matter as long as they're keeping track of progress accordingly.

![2_annotation-tool__annotated](https://user-images.githubusercontent.com/857711/89072407-5918ad80-d32d-11ea-9ab3-a0a2cd2a4c18.png)

- (7) If you end up correcting some annotations, the image you're on will no longer belong to the search set, since annotations will have been updated later than 2020/06/12. This won't affect your ability to proceed with the Prev/Next links, though. The numbers will just look a bit weird. For example, clicking Next could take you from '3 of 20' to '3 of 19'.
    
- (8) For example, if you are going in ascending-date order and the current image's annotation date is 2019/11/01, then next time you can do your step (1) search from 2019/11/01 to 2020/06/12 to continue where you left off.

## Other uses of the proposed search options

To be clear, in the Search box, the rows starting with 'Last annotated' and 'Sort by' are new. Everything above that is not new.

- You can view recent annotation activity in your source by sorting images by annotation date, descending (most recent first). You can further filter it to a particular kind of activity: annotation tool usage, Alleviate, importing, or the automated classifier (unconfirmed annotations).

  - Filtering to classifier activity can give you a slightly better idea of how fast the classifier is adding label suggestions to images, compared to just looking at the unconfirmed-image count.

- If each image is generally handled by a single annotator, then the 'last annotated by' filter lets you count how many images were done by a particular annotator. Or, sorting by annotation date, you can see recent activity by that particular annotator.

  - The already-existing 'annotator' filter in Browse Patches also lets you count a particular annotator's work, except that you get a count of annotations instead of images.
  
## UI concerns

Browse page
  
- Are there enough use cases to justify the added space in the search box?

- Should part of the search box be hidden by default and expandable, under text like 'More filters'?

- Perhaps the sort method should be more visually separated from the filters? Or is the horizontal rule good enough.

Annotation tool

- Maybe not the highest priority, but ideally, the text that shows the currently applied filters would show not only the active filter fields, but also those fields' values. For example, not just "last annotated" but "last annotated = 2019-07-30 to 2020-06-12". Clearly though, that would mean we'd be running out of room in that small horizontal space.
  
  - I think it makes sense to keep this filter display close to the Prev/Next buttons, so I'm not sure about moving this display further down the page.
    
  - We could maybe truncate the filter display and provide a "See all" button, which pops up a modal dialog with the rest of the filters.

**Comment by beijbom** [comment]
Thanks for looking at this @StephenChan . I stand by my previous position in that we need to de-scope this detour. Yes, we made a mistake, and yes, it is possible that some data is corrupt, but frankly, I highly doubt that any user would go back and inspect 1000's or 10000's of images regardless of how easy we do it for them. So I suggest we look forwards instead and move on to other things on the laundry list. 

Per my original post, I suggest we announce the mistake and publish the list of sources. If people want to check their sources they can filter on current meta-data fields or we can send them a text file with URL links to images that are in the relevant date-ranges. My guess is that few, if any, users will get back to use with a request to double-check their images.

End of the day this is a free service run by a shoe-string team and I just don't think this is the best use of our time.

**Comment by kriegman** [comment]
Stephen,

You put a lot of thought in this.

How much effort would go into the implementation of this? Is there a
minimal implementation?

I differ from Oscar's opinion if it's not a lot of work. Producing files
with list of sources, sending them, and fielding questions may be more work
than implementing the filters. Most of this seems like describing a
workflow, rather than  an actual implementation, but I didn't follow all
the details.

One comment -- if "last_annotation.annotation_date" looks a new database
entry.  Isn't this something that can be
computed on the fly as a database query? If so, wouldn't it be better to
compute it on the fly rather than having
to maintain  and constantly update it.  I defer to your opinion  since you
know the codebase/schemas. Just trying to keep it simple and reduce
technical debt
unless it's useful elsewhere or speeds up queries elsewhere.

David

**Comment by StephenChan** [comment]
(Sorry for the delay again. I think I'm back for real now.)

I should mention that we had a meeting in July (which didn't fit in your schedule, Oscar) where David and I ended up discussing at length about the potential user workflow for inspecting affected images.

So my previous post did mostly focus on the workflow, and on designing features which are not too bespoke to the zoom issue.
    
To hopefully be more clear, here's the scope of the potential UI changes:

- Two extra lines of fields in the Browse Search box:

    - 'Last annotated' line.
    
    - 'Sort by' line. We already wanted this in issue #46.

- Additional 'Last annotated' detail line at the bottom of the annotation tool.

And here's the implementation burden:

- Add the filters and sort method to the Browse Search UI. (This is mostly done actually. Sorry, I kind of cheated - I felt more like coding than drawing mockups.)

- Actually apply the filters and sort method to the search results. (Already did a little code cleanup in preparation for this.)

- Add a `last_annotation` database field, saved per Image. Populate the field initially with a data migration. Keep it updated with a post-save signal and a post-delete signal, maybe 5-10 lines each.

> [David:] One comment -- if "last_annotation.annotation_date" looks a new database entry. Isn't this something that can be computed on the fly as a database query? If so, wouldn't it be better to compute it on the fly rather than having to maintain and constantly update it. I defer to your opinion since you know the codebase/schemas. Just trying to keep it simple and reduce technical debt unless it's useful elsewhere or speeds up queries elsewhere.

Yes, it would be a new database field that would be redundant with existing database info, but necessary for speeding up the filters.

I tried some ways of computing the date on the fly and filtering images that way, but the queries always took multiple minutes on large sources. Which certainly isn't ideal for the image search function, since you'd be waiting multiple minutes every time you click next page on Browse, or next/previous image in the annotation tool.

> [Oscar:] Yes, we made a mistake, and yes, it is possible that some data is corrupt, but frankly, I highly doubt that any user would go back and inspect 1000's or 10000's of images regardless of how easy we do it for them.

Well, at that scale, I also highly doubt that to be honest. But checking a subset of images would be pretty reasonable, perhaps a dozen from each site/habitat, from each annotator, or something like that - as long as the affected images are searchable that way. If they don't spot serious problems after that, chances are they're in the clear, even if they annotated 5000 images in this time period. If they spot some bad annotations, and they're uneasy about that, then they can check more.

Part of the idea here is just that source owners can get a good overview of which data was potentially affected, and hopefully narrow down the search to a small set of suspect images. That's not so easy to do with a flat list of 1000 image IDs.

> [Oscar:] I suggest we announce the mistake and publish the list of sources. If people want to check their sources they can filter on current meta-data fields or we can send them a text file with URL links to images that are in the relevant date-ranges. My guess is that few, if any, users will get back to use with a request to double-check their images.

> [David:] Producing files with list of sources, sending them, and fielding questions may be more work than implementing the filters.
    
Okay, to be honest here, I don't think I gave this route enough thought before:

- Yes, we could ask people to contact us if they wanted to see their affected images, and I could use a Python function with a source ID as input, and perhaps an HTML file of affected-image links as output. As long as we don't get too many follow-up questions, I could see myself handling request emails quickly like this.

- The current metadata fields, despite not having anything about annotation date, would probably be sufficient for many source owners. I imagine many research groups have some kind of records or recollections about which sets of images were annotated when. Annotators spend a lot of time staring at these images, after all. Thus, chances are the amount of requests would indeed be smaller than we think.

If I'd realized all that a month ago, then the effort saved could very well have outweighed the inconvenience to source owners for the time being. And maybe I'd be finishing up the vision backend tests by now.

But to also be honest, the hard part is already done with the proposed extra filters. We have a DB design, UI design, workflow, and even UI implementation. The remainder of the coding doesn't require much motivation for me to finish up.

However, even if we don't add the extra filters, much of what I've done was cleanup and generalization of some old filters' UI implementation, so much of the work so far could be useful to keep either way.

By the way, the "Other uses of the proposed search options" in my previous post haven't been addressed yet. I know those uses aren't a high priority right now, but it's worthwhile to assess whether the filters are too bespoke to the zoom issue. What do you think on that front?

**Comment by kriegman** [comment]
It sounds like you're pretty far along the implementation. And you answered
my question about computing it on the fly.

The new filtering options seem useful to me since it will give more
flexibility and oversite, especially for power users/larger institutions
with multiple annotators.

The "sort by" is something that was on my list of things to add, and I
think I had mentioned it.
So, worthwhile features.

Being so far along, it does seem like you should take it to the finish
line. And for the long term, we've got some new features.

David

**Comment by beijbom** [comment]
Thanks @StephenChan . Ok, sounds like you are mostly all the way there, so let's go for it :)

**Comment by StephenChan** [comment]
Sounds good. I'll continue along this path then.

Also: I've mainly been considering the zoom issue. For the rotation issue, it may still be worthwhile to offer list(s) of the 239 images that were rotated 180 degrees, and the 4 images that were nearly square. The reason is that anyone using Safari or Firefox would only have to worry about the rotation issue, not the zoom one.

**Comment by StephenChan** [comment]
This is finally done: https://coralnet.ucsd.edu/blog/annotation-tool-bug-fixes-follow-up-checking-potentially-affected-images/
