### ISSUE TITLE
Problems with EXIF-rotated thumbnails

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#332]
Branched off from #107. Our generated thumbnails take EXIF orientation into account, in the sense that easy-thumbnails rotates the pixel data and then strips the EXIF tag when generating the thumbnail.

It's been this way for a long time. easy-thumbnails had thumbnails using EXIF orientation all the way back in [2011/12/05](https://github.com/SmileyChris/easy-thumbnails/commit/cfb6b8b2ae49f2ff2bad19ab20ee793cc755e3c3)! That was before their version 1.0 release in mid-2012.

However, we actually had easy-thumbnails installed previously as an alpha version, since it was a [django-userena](https://github.com/bread-and-pepper/django-userena/blob/1601c2ab7c573ebb403ecf8e51c978a6360f759d/setup.py) requirement. [Here's a 2011/08/06 commit](https://github.com/beijbom/coralnet/commit/43d084f25b32c67d02577a8e84be2156dc587664) of ours using easy-thumbnails. I'm not sure what our easy-thumbnails update history looks like, unfortunately. It's actually plausible that we stuck with our mid-2011 installed alpha version for quite a while.

Anyway, this behavior in itself isn't necessarily a bad thing, but there are a few problems related to the situation:

## Problems

1. The annotation area edit UI uses a thumbnail, so EXIF orientation is applied if it's present. However, the edit UI doesn't take EXIF orientation into account. So the thumbnail gets stretched to fill the space that the un-rotated image would have filled.

   <img src="https://user-images.githubusercontent.com/857711/84535330-796aab00-aca0-11ea-8963-30797558ea85.jpg" width="400">
   
2. For a long time, easy-thumbnails didn't handle EXIF orientation correctly in the 90 degree rotation case. Basically, the image content gets rotated in the correct direction, but the content gets saved into the unrotated aspect ratio. So part of the image gets cut off, and it ends up with black bars.

   Example of an original image, displayed here WITHOUT its 90-degree EXIF rotation:

   ![thumbnail-black-bars_original](https://user-images.githubusercontent.com/857711/84584480-d5752280-adb9-11ea-9098-89635fecabb8.jpg)

   And its thumbnail:

   ![thumbnail-black-bars_thumbnail](https://user-images.githubusercontent.com/857711/84584481-d908a980-adb9-11ea-9763-1c723340c3d4.jpg)

   This behavior was present from 2011/12/05 (in terms of easy-thumbnails' master branch) until [easy-thumbnails 2.4.1](https://github.com/SmileyChris/easy-thumbnails/blob/master/CHANGES.rst). We merged a PR updating to 2.4.1 or later on [2019/08/01](https://github.com/beijbom/coralnet/pull/218). And I'm not sure if we updated production shortly after that. We can probably say this was fixed in production between August and October.

   So any thumbnails generated on EXIF-rotated images before August-October 2019 could be buggy. 

3. Per issue #107, we are reverting our display of full images to ignoring EXIF orientation, for annotation tool consistency. But this means the thumbnails appear rotated, and the full images appear unrotated.

   That can be confusing, especially since the annotation tool loads a smaller thumbnail first for responsiveness, then swaps in the full image once that's loaded. The image swap looks fine if it just goes from a grainy image to a more crisp one. But if there's EXIF orientation, it appears to swap a completely different image.

## Potential solutions

1. easy-thumbnails has some kind of setting to rotate thumbnails according to EXIF orientation or not. It defaults to True. So we can pass False to not rotate thumbnails, thus solving problem 1 (area edit) and problem 3 (consistency with full images) for newly generated thumbnails. https://easy-thumbnails.readthedocs.io/en/latest/ref/source_generators/

2. Thumbnails are regenerated on demand if they're deleted. So, for all images with non-default EXIF orientation, we can just delete the thumbnails and let them get regenerated as needed. This will fix problem 2 (black bars thumbnails), as well as problems 1 and 3 for old thumbnails.

**Comment by StephenChan** [comment]
Solution 1 is in PR #338.

Solution 2 is (probably) a one-time run, so I'm not adding it as a management command, but it would look something like this:

```python
from collections import defaultdict
import struct

from django.core.files.storage import DefaultStorage
from easy_thumbnails.models import Thumbnail
import piexif
from PIL import Image as PILImage
from tqdm import tqdm

from images.models import Source

storage = DefaultStorage()

no_file = []
no_exif = 0
broken_exif = 0
broken_exif_sources = set()
exif_without_orientation = 0
exif_with_default_orientation = 0
exif_with_non_default_orientation = 0

thumbnail_files_deleted = defaultdict(int)
thumbnail_objs_deleted = defaultdict(int)
thumbnail_suffixes = [
    '.100x100_q85.jpg',    # map source detail
    '.150x150_q85.jpg',    # browse images
    '.300x300_q85.jpg',    # source main page
    '.450x450_q85.jpg',    # front page carousel
    '.800x0_q85.jpg',    # image_detail, annotation area edit, annotation_tool
]

for source in tqdm(Source.objects.all().order_by('pk')):

    source_id = source.pk
    
    for image in source.image_set.all():
        
        try:
            pil_image = PILImage.open(image.original_file)
        except IOError:
            no_file.append(image.pk)
            continue
        
        if 'exif' not in pil_image.info:
            # PNG, or JPEG without exif
            no_exif += 1
            pil_image.close()
            continue
            
        try:
            exif = piexif.load(pil_image.info['exif'])
        except struct.error:
            broken_exif += 1
            broken_exif_sources.add(source.pk)
            pil_image.close()
            continue
        
        if piexif.ImageIFD.Orientation not in exif['0th']:
            exif_without_orientation += 1
            pil_image.close()
            continue
            
        orientation = exif['0th'][piexif.ImageIFD.Orientation]
        pil_image.close()
        
        if orientation == 1:
            exif_with_default_orientation += 1
            continue
            
        exif_with_non_default_orientation += 1
                
        for suffix in thumbnail_suffixes:
        
            thumbnail_path = image.original_file.name + suffix
            if storage.exists(thumbnail_path):
                storage.delete(thumbnail_path)
                thumbnail_files_deleted[suffix] += 1
                
            # If the Thumbnail object is not deleted as well, the thumbnail
            # file won't get regenerated even when it's needed on a page.
            try:
                thumbnail_obj = Thumbnail.objects.get(name=thumbnail_path)
                _ = thumbnail_obj.delete()
                thumbnail_objs_deleted[suffix] += 1
            except Thumbnail.DoesNotExist:
                pass
```

Then you'd look at the various stats like `thumbnails_deleted` to sanity-check.

easy-thumbnails does have a `delete_thumbnails()` method which would have simplified the last part of the above code. However, it doesn't seem to work for us in all cases, possibly related to this issue: https://github.com/SmileyChris/easy-thumbnails/issues/357
I also found `get_existing_thumbnail()` to be finicky with S3.

**Comment by StephenChan** [comment]
I modified the above code to catch a `ValueError` case as well. All production images have been looped through, with total runtime being about 3 days and 15 hours. Cleaned up around 100,000 thumbnails. So I think that completes this issue.

**Comment by kriegman** [comment]
👍
