### ISSUE TITLE
Show last-saved and last-trained classifier dates on source main page

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#341]
A simple solution for part of issue #159, suggested by Veronica Radice on the Google Group:

> Perhaps the wording on the source home screen could be revised from "Last classifier trained" to "Last classifier saved" to reflect how it works? An additional date/time stamp for the true "Last classifier trained" category would be great, so users are aware of the training as it occurs.

She's referring to the first gray box on this page - which I completely forgot had this timestamp, to be honest. If that seems easily missable, we could instead consider placing this info between the "Automated Annotation" header and the line plot.

**Comment by StephenChan** [comment]
@beijbom What do you think of this?

**Comment by beijbom** [comment]
Sorry for chiming in late. I love this idea. Simple yet powerful. @StephenChan : u want to take this one? Otherwise, I can do it. 

(I had also forgotten we show that piece of information!).

**Comment by StephenChan** [comment]
@beijbom If you've got time this week or the coming weekend, then feel free to do it, otherwise I can take it.

**Comment by beijbom** [comment]
Sounds good. I'll see if I can squeeze it in.

**Comment by StephenChan** [comment]
This is working as far as I can tell.
