### ISSUE TITLE
Move spacer to AWS Batch

### ISSUE THREAD

**Issue by beijbom** [beijbom/coralnet#346]
Try using AWS batch instead of the current ECS based backend. This will require some minor changes to spacer, some AWS config work and also some change to how CoralNet submits the jobs.

- [x] Configure AWS Batch. https://us-west-2.console.aws.amazon.com/batch/home?region=us-west-2#/dashboard
- [x] Add AWS Batch bindings to spacer. https://github.com/beijbom/pyspacer/pull/29
- [x] Migrate spacer to `boto3`. Make secure store feature. Make `TrainClassifierMsg` standalone.
- [x] Integrated in CoralNet.

**Comment by beijbom** [comment]
@StephenChan @kriegman : I added this ticket for myself. After conferring with the AWS folks, this seems like a much cleaner way compared to the current setup. It would basically only require interfacing with AWS Batch (plus possibly 1 SQS queue for reading back the results). So it's worth a shot as it'd make the AWS config much more maintainable. I might even try to setting the whole thing up using the CLI.

**Comment by StephenChan** [comment]
Sounds good - looking forward to seeing how it goes.

**Comment by beijbom** [comment]
First PR create here: https://github.com/beijbom/pyspacer/pull/29. CC @StephenChan @kriegman.

I'll do one more PR on spacer, and some more testing before updating the CoralNet feature branch. So for it's looking quite good.

**Comment by StephenChan** [comment]
This appears to be done, but I guess we can check that it works in production first.

**Comment by StephenChan** [comment]
Looks like the AWS Batch setup is working smoothly overall. No recent reports of tasks not getting done. Guess it's time to close the 1.0 milestone, then!

I think it's worth looking into reducing the number of dev emails related to jobs not getting completed, but that can be addressed in a separate issue.
