### ISSUE TITLE
Stats exports: include summary stats

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#373]
At the bottom of the exported CSV, add a single row with the following info:

- Image Covers, CSV: percent coverage of each label, taken over all the images in the export
- Calcification rates: Calcification rate averaged over all the images in the export. As well as the export-wide contributions from each label, if the relevant optional columns are enabled.
- Other export types: Not applicable (as far as I can think of)

I believe this has been requested a few times over the years for the Image Covers CSV export, and our response was that people can compute the summary stats themselves with basic knowledge of Excel formulas. Which is true, but it's not too difficult for us to include it in the CSV, either - and part of the calcification-rate plans include displaying the latest summary stats somewhere on the source (#375), which means we want to compute said summary stats anyway.

Two possible methods of averaging:

1. Compute stats for each image and then average over all images.
2. Compute stats for each point-annotation and then average over all point-annotations.

If each image in the source has an equal number of points, and each image's annotation area covers roughly the same area of the benthic zone, then either 1 or 2 should be valid. If the source is set up differently, it's possible that one averaging method could be more valid than the other, but I'm not sure if any other source setups are common on CoralNet. So I suppose we just pick one method of averaging and go with it (and update the help text to clarify how it's done).

**Comment by traviscourtney** [comment]
I think it would be nice to have the exported summary statistics for the mean, lower, and upper calcification rates so the confidence bounds are included in any summary calcification rates so that there's easy user access to the calcification rates and uncertainties for their project.

**Comment by StephenChan** [comment]
I didn't specify that clearly here, but you're right - mean, lower bound, and upper bound should be included in the summary. If there are columns for each of those 3 (as specified in #369), then the summary-stats row specified in this issue should be able to have numbers for all 3.

**Comment by StephenChan** [comment]
Done in #404 (calcification) and #405 (image covers).
