### ISSUE TITLE
Write tutorial on using calcification rates functionality

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#378]
Including tips on filtering images by aux. metadata fields, in case some images are in the Atlantic and some are in the Indo-Pacific region.

The tutorial would live here: https://coralnet.ucsd.edu/pages/help/tutorials/

**Comment by traviscourtney** [comment]
Do we have any sense for how likely are we to see multiple locations within a given source? Regardless, I think it is good to explicitly address this in some way on the tutorial pages to improve clarity for using the tool as much as possible.

**Comment by StephenChan** [comment]
That's a good question. My impression is that the vast majority of sources focus on a specific region, and off the top of my head I can't think of a large/high-quality source spanning two or more completely different regions. It's technically possible, of course, but I guess it's not common at all.

I suppose a brief explanation of filtering images by metadata is still helpful, but it doesn't have to be in the context of "use Atlantic table for one image set and Indo-Pacific table for another image set."

**Comment by StephenChan** [comment]
Tutorial is up: https://coralnet.ucsd.edu/pages/help/tutorials/calcification/

Can be edited/reworked later as needed, but it's basically complete.
