### ISSUE TITLE
Human annotations vs. confirmed annotations confusion

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#428]
Regarding this function, `image_has_any_human_annotations()`: https://github.com/beijbom/coralnet/blob/e4a53e2e75d2d3fee879343a14bf2b75dac90ad3/project/annotations/utils.py#L29

The function definition matches the function name: it checks if the image has any annotations not made by Robot or Alleviate.

However, the function's usages have varying degrees of correctness, and I feel that "Has any confirmed annotations" is generally what we'd want instead. Note that Robot annotations are unconfirmed, while Alleviate annotations are confirmed.

Usages:

1. On the image-detail page, the image is said to be "Complete" if it has all confirmed annotations, "Partially annotated" if it has any human annotations, and "Not started" otherwise. Of note, if it has some annotations confirmed by Alleviate, it would still say "Not started". Technically this can be correct, in the sense that annotation hasn't been started by a human - but since CoralNet logic generally only makes the distinction between confirmed and unconfirmed (not human vs. non-human), it seems kind of misleading. "Has any confirmed annotations" seems like a more consistent way to define "Partially annotated". https://github.com/beijbom/coralnet/blob/e4a53e2e75d2d3fee879343a14bf2b75dac90ad3/project/images/views.py#L484

2. On the image-detail page, the "Delete annotations" button is only available if the image has any human annotations. This means that even when the image has been fully annotated by Alleviate, it won't be possible to delete the image's annotations from this page. This is something a user might want to do if they accidentally set a too-lenient Alleviate confidence threshold, for example. I think this logic would really be better as "has any confirmed annotations". https://github.com/beijbom/coralnet/blob/e4a53e2e75d2d3fee879343a14bf2b75dac90ad3/project/images/templates/images/image_detail.html#L127

3. An image's annotation area cannot be edited if there are any human annotations. I think this usage is reasonable. Though, it wouldn't make a big difference if the logic were "if there are any confirmed annotations" instead, since one could always delete any Alleviate annotations first, and then edit the annotation area. https://github.com/beijbom/coralnet/blob/e4a53e2e75d2d3fee879343a14bf2b75dac90ad3/project/annotations/utils.py#L50

I propose changing the logic in all three cases to "has any confirmed annotations" for A) fixing the usability issue in point 2, and B) improving consistency and simplicity.

**Comment by beijbom** [comment]
Thanks for looking into this. I agree with the suggestion!

**Comment by StephenChan** [comment]
Changes made in PR #431.
