### ISSUE TITLE
API and account

### ISSUE THREAD

**Issue by maxcorsini** [beijbom/coralnet#471]
Dear all,

I am trying the API to use existing classifiers, but when I try to authenticate I receive a message that I cannot
(but my account works good). 

There is something I am missing ? 

Thank you very much.

**Comment by StephenChan** [comment]
Hi there - how are you trying to authenticate? For example, are you using a `curl` command like step 1 of our tutorial?: https://coralnet.ucsd.edu/pages/help/api/tutorials/ Or are you using a snippet of code instead.

Also, what's the error message that you're getting?

**Comment by maxcorsini** [comment]
Thank you! I have solved, the problem was that under Windows I have backlash the quotes.

**Comment by maxcorsini** [comment]
Another question, the pretrained weights of the EfficientNet are available ? Thank you.

**Comment by StephenChan** [comment]
Ah, glad you found the issue!

We're currently sharing the EfficientNet weights download-link on a request basis. Maybe I can provide you the link by email? I think we might already have each other's email addresses from a group meeting a while ago.
