### ISSUE TITLE
Question: Getting access to total number of requests sent to API 

### ISSUE THREAD

**Issue by Jordan-Pierce** [beijbom/coralnet#474]
Hi @StephenChan @beijbom, 

Using the API for model predictions, how can one determine the total number of active jobs that have been deployed to a source's model? I understand that we're limited to 5 at a time, and after trying to submit a 6th while 5 are currently active, it will be rejected. 

If the total number of active of jobs is known on your side, what request can we send to CoralNet to know how many are currently active before trying to deploy another?

Thanks,

Jordan

**Comment by Jordan-Pierce** [comment]
For example, below I'm creating a payload and sending a job using POST:
```python
# Create a payload for the current image
payload = {}
payload['data'] = [{"type": "image",
                    "attributes":
                     {
                        "name": image_name,
                        "url" : image_url,
                        "points": points
                      },
                  }]

job = {
        "image_name": "",
        "model_url": MODEL_URL,
        "data": json.dumps(payload, indent=4),
        "headers": HEADERS
      }

# Upload the image and the sampled points to CoralNet
print(f"NOTE: Attempting to upload {job['image_name']}")
response = requests.post(url=job["model_url"],
                         data=job["data"],
                         headers=job["headers"])

print("Status Code: ", response.status_code, response.ok)

if response.ok:
    print(f"NOTE: Submitted {job['image_name']}")
else:
    message = json.loads(response.text)['errors'][0]['detail']
    ids = re.findall(r'IDs: (.+?)\)', message)[0].split(', ')
    print(f"NOTE: Current jobs are still active: {ids}")
    
```

If there are currently active jobs, the final line will print:
```python
NOTE: Attempting to upload 
NOTE: Current jobs are still active: ['21708', '21709', '21710', '21711', '21712']
```

But I can't seem to find a way to get a response from CoralNet with the number or IDs of active jobs without actually submitting another job and catching an error. It'd be great if a user could submit a passive request to CoralNet given their header information and model ID and just get that information in return before trying to submit additional jobs.

**Comment by StephenChan** [comment]
Hi Jordan, apologies for the late response - at this point there isn't a passive request that gives you the number of active jobs. The options you have would be to either try another upload (as you've shown), or to query `api/deploy_job/<id>/status/` for each of the job IDs which you previously knew were active.

We've had an idea at issue #294 which is related - giving a webpage which has status info like this. But having the info at a JSON API endpoint as well would be ideal.

Also, for the record, the limit of 5 active jobs is per user, not per model.

**Comment by Jordan-Pierce** [comment]
@StephenChan thanks for the reply, no worries at all.

I ended up creating a queue system on my side to deal with this, and essentially if for some reason a job was active prior to running the script/notebook, it'll keep waiting/requesting a new job once there is a spot available for it (in case others are interested, lemme know, happy to share/help).

With regards to the number of active jobs available for a single user, is there a way we can have access to more? Specifically, I'm working on a project with NOAA and investigating using CoralNet's API for one of our workflows. If it does it end up being an effective method for what we are trying to achieve, can I get in contact with you or others offline to talk about this?

**Comment by kriegman** [comment]
Hi Jordan,

As you probably know, NOAA has been one of the major funders of CoralNet,
and so we're very responsive to requests for capabilities that support NOAA
research and when that research or workflows requires scaling, we can
figure out what makes sense to implement. Obvious considerations are
implementation cost/effort, maintainability and impact on operating costs.

BTW: I just peaked at our API logs. It looks like you're processing  one
image at a time. The API supports "100 images per request, 200 points per
image" See https://coralnet.ucsd.edu/pages/help/api/reference/

That can provide much higher throughput that you probably need and might
meet your requirements.

--David Kriegman

**Comment by kriegman** [comment]
I’ll have to let Stephen or Oscar provide more details but based on the
load we spin up about 100 workers dynamically. For computing features and
classification. I’m not sure how many threads are used to fetch images,
extract patches and send them to inference engine.

@stephen it would be worthwhile to do some systematic experimentation and
report how throughout scales with number of images per call and points per
image. Results will be dependent on image size and bandwidth but would
provide some guidance. Perhaps this effort makes sense in the context of
the WCS project…not something that will be done in the near term.

**Comment by StephenChan** [comment]
We give one image's entire workload (from download to classification) to a single worker instance, and yes, we can have a bunch of instances running in parallel, which means potentially multiple downloads in parallel.

But indeed we haven't done measurements to see how this performs, like how many parallel downloads we can have until it starts slowing down each download. Yeah, that would be good to do experiments on.

**Comment by Jordan-Pierce** [comment]
Thanks @StephenChan, just to clarify the following:

> **We give one image's entire workload (from download to classification) to a single worker instance, and yes, we can have a bunch of instances running in parallel, which means potentially multiple downloads in parallel.**
> 
> But indeed we haven't done measurements to see how this performs, like how many parallel downloads we can have until it starts slowing down each download. Yeah, that would be good to do experiments on.

Each user only has access to use 5 worker instances at one time? So even if a post request contains 100 images, only the first 5 will go from download to classification, and when one of those finishes, another one will start the download to classification process?

**Comment by StephenChan** [comment]
It's up to 5 outgoing requests, and each request can have up to 100 images, so you can actually have up to 500 images queued at once. Now, if you do request 500 at about the same time, then they won't all be able to get allocated to worker instances immediately, but they'll get onto the queue and will start processing when enough of the other images finish processing.

**Comment by Jordan-Pierce** [comment]
@StephenChan thanks for the clarification!

**Comment by Jordan-Pierce** [comment]
Just coming back to comment that yes, the ability to send 100 image urls per the 5 requests we're allocated helped a lot. Thanks.
