### ISSUE TITLE
Ensure every reachable page has a unit test for every relevant permission level

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#54]
I think we already have some good progress toward accomplishing this, but I just haven't been keeping score or anything.

This issue is twofold:
- Write unit tests for more pages, and make sure to cover different permission levels (not logged in, source edit, superuser, etc.).
- Figure out how to keep better track of what we've tested. Look into Python or Django test coverage apps?

**Comment by beijbom** [comment]
@StephenChan : can we close this & mark as done in project? Or are there more outstanding items?
