### ISSUE TITLE
Upgrade codebase from Python 2.7.x to Python 3.x

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#59]
## Motivation: End of support for Python 2, in both Django and Python itself

* Python 2.x end of support is [January 1, 2020](https://pythonclock.org/). It won't get security updates after that.
* Django 1.11.x is the last version to support Python 2.x. Django 1.11.x's end of support may be as early as [April 2020](https://www.djangoproject.com/download/). Django 2.0 onward only supports Python 3.x.
* In addition to Django dropping Python 2 support, we can expect other third-party Python packages that we use to drop it as well.

## Which version to target

Python 3.6.

Python 3.4's end of life is [March 2019](https://docs.djangoproject.com/en/dev/releases/2.0/), even earlier than Python 2.7's end of life. 3.6.x is the latest stable version as of 2018.05.11. See other versions' end-of-life dates [here](https://devguide.python.org/#status-of-python-branches).

So from there the question is 3.5 or 3.6 based on third-party package support. As it turns out (#185), all of our third-party packages support 3.6, so we should aim for that.

## How to update our codebase

The trickiest part is Unicode strings vs. byte strings. Fixing our code for that often requires a good semantic understanding of the code we're looking at, so it's tough to just go through the whole codebase at once and fix that. I propose that we gradually make this change while working on other features like the API.

For other 2-to-3 changes, it's probably easier to change the whole codebase at once so we don't have to keep those changes in mind anymore. But... we should write more unit tests first.

- Details on 2 vs. 3 differences
  - https://docs.python.org/3/howto/pyporting.html
  - http://python-future.org/compatible_idioms.html
  - Use the `six` module to write code compatible in both Python 2 and 3. See the [six docs](https://pythonhosted.org/six/).
    - I'm not actually using the `future` package since it doesn't offer that much more benefit over six, IMO, and PyCharm inspections didn't seem to play nice with future when I tried it.
- Also see the changelogs for later 3.x versions, but don't use 3.x-only features yet (that's for #186)
- Use the PyCharm inspections which check Python version compatibility.
- Ctrl+F our project for mentions of "Python 2", "Python 3", etc. in comments. I left at least a couple of comments like that.
- Starting in Django 1.10, Unicode usernames are supported when using Python 3.x. We must decide whether to allow Unicode usernames or add our own validator to ensure it's ASCII only. (Most likely we'll stick with ASCII usernames for simplicity.)
- Ensure our unit test suite is thorough. If all tests pass on Python 3, and the server runs fine on Python 3 in general, then we are ready to upgrade to Python 3.

## How to run the website on Python 3

The website must be able to run off of a Python 3.x virtualenv.

For now, while we are doing a gradual refactor, it's ideal to maintain two virtualenvs, one Python 2.x and one Python 3.x, so we can test either one whenever we want. Just activate the appropriate virtualenv, and you'll run any Django management commands (test, shell, runserver, etc.) and pip commands on that env's Python version.

It's also ideal to get 3rd party Python packages to versions supporting both Python 2 and 3. (Except supervisor, which runs separately from Django, and thus has no Python version requirement for this issue's purposes.) See #185 for individual packages' support details.

Note that pip is part of Python by default starting from Python 3.4, but platform packagers can still choose not to include it by default. Just be aware that the installation procedure might change slightly.

To update the production server to Python 3:
- Install Py3 with apt-get
- Create a new virtualenv for Py3 and install things on it
- Ensure supervisor, gunicorn, etc. run Django-server commands using Python 3.
- Do the usual server code update procedure. If the supervisor config was changed, restart supervisor as well. (Should be `sudo stop supervisord`, `sudo start supervisord`)

Another update reference here: https://stackoverflow.com/a/17954487/

## Django support of Python 3

Not a problem, even before upgrading to Django 2.0. At our current Django version of 1.9.x, Django has already supported Python 3.x for quite a while (I think since Django 1.6?).

**Comment by StephenChan** [comment]
Some thoughts on rolling this out. Trying not to speak for the whole spacer transition process until we discuss that further, but trying to organize my thoughts stopping short of that.

I think this is what an **ideal** Python 2-to-3 transition would look like:

1. Get our entire project to the point where it works in both Python 2.7 AND 3.x simultaneously. 

   - For our own code, stuff like `__future__` imports, the `six` package, and try-except in import statements generally make this possible.

   - For 3rd-party packages, every package needs to be at a version that works in 2.7 and 3.x, for the SAME 3.x. For example, hopefully every package has a version that works in both 2.7 and 3.5.

   - Ideally, our unit tests cover almost all of our functionality, they all pass in 2.7, and they all pass in 3.x. To test this, we maintain two different virtualenvs on our dev machines, one for each Python.

   - Whenever I mentioned 'porting' the code from Py2 to Py3 in the past, that wording might've been misleading. That wording fails to imply this (potential) transition phase where the code would work in both 2 and 3. Overall, I think I've been sloppy/confusing when talking about this whole transition process. Hopefully I can straighten things out in both my head and my wording.

2. Leisurely swap all of our environments (production, dev, etc.) from running Python 2.7 to running Python 3.x. Make sure things are stable and working.

3. When things seem stable and working, we can start cleaning up any code that was only needed for Python-2.7 compatibility, and we can start using 3.x-only features.

Of course, the hard part is the first step. Two major concerns:

1. Some vision backend functionality can't be covered by unit tests until issue #264 is complete. That issue might not be done until the codebase is Py3-compatible in the first place. So, after making the vision backend Py3-compatible, the backend would be prone to bugs until 264 and associated tests are completed.

2. It may not be possible to satisfy this: "For 3rd-party packages, every package needs to be at a version that works in 2.7 and 3.x, for the SAME 3.x." For example, if one package jumps straight to Py3.5 or higher in its first Py3-supporting version, and another package restricts to Py3.4 or lower in its last Py2-supporting version, then we may be out of luck.

   - From what I've seen, most packages don't enforce a maximum Py3.x version in `setup.py`. So even if the package was released when Py3.4 was the latest, it might still be installable on Py3.5. We'll have to see if that holds true for all of our packages, though. Also, even if the package's `setup.py` doesn't have this kind of restriction, we don't know if the package will actually install and work on later Python versions until we try it.

   - If we are very close, but only one or two simple 3rd-party apps are blocking us, we might consider a temporary hack: copy the app's code into our codebase temporarily, and monkey-patch the part that's blocking compatibility. Once the Py3 transition is done, we can go back to using an unmodified version of the package.

If either of those two concerns makes simultaneous Py2+Py3 support infeasible, then our transition process becomes more ugly. Though of course, there's still a matter of how much ugliness is left (1 3rd-party app, or 1% of the codebase, etc.) which would affect the smoothness of the transition.

**Comment by StephenChan** [comment]
Not really sure if this issue should be in the prereqs or rollout milestone. But it should be in at least one. At any rate, PR #309 would address a large chunk of this.

**Comment by beijbom** [comment]
Prerequisite is right.

**Comment by StephenChan** [comment]
Calling this done after PRs #309 and #312.

I'll repeat here for the record that misc. scripts have not been ported: `images/scripts.py`, `vision_backend/scripts.py`, and contents of the `scripts` folder at the repo root. Those can be done later or as needed.
