### ISSUE TITLE
Update to boto3

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#82]
I was previously wondering if this would involve replacing `django-storages` with some other solution, but it turns out that `django-storages` just added boto3 support in August. (See their journey here: https://github.com/jschneier/django-storages/pull/111) Looking at their [changelog](https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst), getting boto3 support means upgrading to `django-storages` 1.5.0 or later.

I read in an issue or two that the `django-storages` readthedocs site may be out of date, so I'm not sure if any configuration changes are needed to make it work with boto3. So it'll be worth perusing their repo and issues a bit more to confirm this.

We also have some direct calls to boto, mainly related to Amazon SQS. Those will certainly have to be edited to move from boto 2 to 3. Note that according to [boto's README](https://github.com/boto/boto/blob/5e176f5d037912018f7b36f00d2cfe41dd4a2d62/README.rst), boto3 "can be used side-by-side with Boto [2] in the same project", so this isn't absolutely necessary to update simultaneously with the `django-storages` boto. It's good to have everything consistent and up to date if we can though.

**Comment by StephenChan** [comment]
Whenever we update to boto3, we can upgrade django-storages to 1.9 or later.

**Comment by beijbom** [comment]
One use-case was removed in this commit: https://github.com/beijbom/coralnet/commit/eb8c1043867b4d804ca6e91318786de39af6a104. The remaining direct calls are used sparingly in management commands. I'll clean those up later.

**Comment by StephenChan** [comment]
Completed with PR #462.
