### ISSUE TITLE
statistics page broken

### ISSUE THREAD

**Issue by beijbom** [beijbom/coralnet#85]
Statistics page crashes on every search. Missing "image_search_args_to_queryset_args". Probably a quick fix somewhere.

message:
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/source/3/browse/statistics/?aux1=&aux2=&aux3=&aux4=&groups=6

Django Version: 1.9.5
Python Version: 2.7.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'easy_thumbnails',
 'guardian',
 'reversion',
 'storages',
 'userena',
 'userena.contrib.umessages',
 'accounts',
 'annotations',
 'bug_reporting',
 'errorlogs.apps.ErrorlogsConfig',
 'export',
 'images',
 'labels',
 'lib',
 'requests',
 'upload',
 'visualization',
 'vision_backend']
Installed Middleware:
['django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'userena.middleware.UserenaLocaleMiddleware',
 'reversion.middleware.RevisionMiddleware']

Traceback:

File "/Users/beijbom/.virtualenvs/coralnet/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                     response = self.process_exception_by_middleware(e, request)

File "/Users/beijbom/.virtualenvs/coralnet/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)

File "/Users/beijbom/sites/coralnet/project/lib/decorators.py" in _wrapped_view
1.                 return view_func(request, _args, *_kwargs)

File "/Users/beijbom/sites/coralnet/project/visualization/views.py" in generate_statistics
1.             imageArgs = image_search_args_to_queryset_args(form.cleaned_data, source)

Exception Type: NameError at /source/3/browse/statistics/
Exception Value: global name 'image_search_args_to_queryset_args' is not defined

**Comment by StephenChan** [comment]
Closing this in favor of issue #422.
